### ISSUE TITLE
Multiple attachments support

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#130]
Let user upload more than 1 file.

**Comment by epicmonkey** [comment]
Already resolved.

**Comment by smallq-git** [comment]
Not resolved: when I ctrl- or shift-click a file, previous selection is removed.

Steps to reproduce:
1. Click Choose File button.
2. Select one file.
3. Press ctrl or shift and click on the next file.

Expected: Both clicked files are selected and are ready to be uploaded.
Actual: Only one file can be selected at a time.

**Comment by clbn** [comment]
I suppose initial title and description for this task reads as "Allow attaching multiple images to one post". Hence the closing it by @epicmonkey. I'd suggest creating another task for your case, with explicit description.

**Comment by smallq-git** [comment]
@clbn As you can see in the log, just below description, the initial title reads "При создании поста можно добавлять файлы только по одному", and that describes the issue that was reported. Ability to attach multiple files had been present at the time of this issue creation but it wasn't possible to select several files at once and upload them in one go. This issue is NOT fixed.

**Comment by clbn** [comment]
@smallq-git Then I suggest changing the title to avoid misinterpretation.
