### ISSUE TITLE
Pictures are not collapsed when there are more than X of them

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#137]
Page https://micropeppa.freefeed.net/#/
Screenshot https://yadi.sk/d/zbd8avOqg3XGy

**Comment by smallq-git** [comment]
According to OnePost description:
Post can contain several pictures, but only last 1-3 thumbnails will be shown (depending on image width), the rest could be viewed by clicking on the blue arrow.

Note: the width should be such that all visible thumbnails are viewed on one line.

**Comment by teinett** [comment]
Post can contain several pictures, but on the post page only last 13 thumbnails will be shown (depending on image width), the rest could be viewed by clicking on the blue arrow.

13 thumbs - on the post page
2 thumbs - in the feeds

**Comment by clbn** [comment]
@epicmonkey Please assign it to me.

@teinett "13"? Is it a typo? I agree with a @smallq-git comment, but yours is confusing.

**Comment by epicmonkey** [comment]
My pleasure! :sparkling_heart:

**Comment by teinett** [comment]
@clbn yes, my mistake. don't make attention to it.

**Comment by indeyets** [comment]
BetterFeed's implementation: https://github.com/davidmz/BetterFeed/blob/master/src/js/actions/fold-images.js

**Comment by urbansheep** [comment]
Actually, FRF went to a great length to not break the visual boundaries of a “post unit” in the feed.

Not last 3, but first 3 pictures had been shown, and when combined thumbnail width exceeded 450px (i.e. when there're wide (landscape/panorama) images) there would be less than three, to a minimum of 1, so that single line of pictures displayed by default would never wrap unless manually expanded.

**Comment by smallq-git** [comment]
Pictures are now collapsed. Waiting for individual post behavior confirmation before marking as verified.

![image](https://cloud.githubusercontent.com/assets/7983303/8387512/a7b6e87c-1c61-11e5-90c3-596cf227e8db.png)

**Comment by clbn** [comment]
@smallq-git I'm not sure I understood. What kind of confirmation do you need?

To clarify: images are not collapsed on an  individual post page, that's intentional.

**Comment by smallq-git** [comment]
@clbn I can see that in the current realization they are not collapsed. In this regard everything works as expected. 

However, I vaguely remember them being collapsed in Frf so I've requested @urbansheep's assistance since he provided information above. Depending on results this issue will be marked as Verified (i.e. fixed, closed and accepted) and either a new issue will be opened or this behavior will remain as is.

**Comment by clbn** [comment]
Ah, you meant someone else's confirmation, not mine! Now I got it, thanks. Sure, let's wait for it and fix the behavior, if needed.

**Comment by smallq-git** [comment]
NP. Thanks for your confirmation as well :)

**Comment by smallq-git** [comment]
@clbn Got confirmation that pictures were collapsing on individual post pages as well and opened separate issue: https://github.com/pepyatka/pepyatka-html/issues/525. Marking this one verified.
