### ISSUE TITLE
Group's username is not found in To: field.

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#270]
Pre-condition: user has created a group (testuser4/testuser4)
1. Log in.
2. On Home feed activate Post box.
3. Click Add/Edit link.
4. Enter group's username.

Expected: Group's username is found and added to the To: list.
Actual: Group's username is not found:

![image](https://cloud.githubusercontent.com/assets/7983303/7339519/52a2f7a2-ec7a-11e4-8927-cea560a7f568.png)

**Comment by epicmonkey** [comment]
Was a new group or already existing one?

**Comment by smallq-git** [comment]
@epicmonkey I'm confused by this question. I've tried it both right after creating a group and after logging out and back in again.

Are you having trouble reproducing it?

**Comment by epicmonkey** [comment]
I'm trying to understand pre-conditions of the defect (e.g. sometimes login/logout is not enough to clear app cache, but reload is a better way doing this). Because different pre-conditions may result into different behaviour, for example this is my screenshot (where group1 and group2 are display names and usernames):
![groups](https://cloud.githubusercontent.com/assets/117683/7358636/8d636d16-ed3f-11e4-83b9-cf1192b3a08d.png)

**Comment by smallq-git** [comment]
@epicmonkey Indeed, hard reload helps. But this still is a bug.

**Comment by epicmonkey** [comment]
Alright, so pre-conditions is "user _just_ created a new group", right?

**Comment by smallq-git** [comment]
Right now it's "user haven't logged out since creating a group"

**Comment by epicmonkey** [comment]
Gotcha!

**Comment by smallq-git** [comment]
Doesn't happen anymore
